/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import control.DataClass;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import static java.lang.Float.parseFloat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import model.Parking;
import model.Plaza;
import model.Vehiculo;
import model.data.enums.EnumColor;
import model.data.enums.EnumVehiculo;
import model.data.exceptions.NotFreePlacesException;
import view.console.Main;

/**
 *
 * @author ivansimmer
 */
public class JFrameHome extends javax.swing.JFrame {

    /**
     * Creates new form JFrameHome
     */
    public JFrameHome() throws NotFreePlacesException {
        initComponents();
        initConfig();
        configParkingGrid();
    }

    private void initConfig() {
        DataClass.JFH = this;
        DataClass.setVisible();
        JLabel labelParking;
        jPanelParking.setBackground(new Color(0,58,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelParking = new javax.swing.JLabel();
        jPanelParking = new javax.swing.JPanel();
        buttonLiberar = new javax.swing.JButton();
        buttonAsignar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 58, 255));

        jPanel1.setBackground(new java.awt.Color(0, 58, 255));

        labelParking.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelParking.setForeground(new java.awt.Color(255, 255, 255));
        labelParking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelParking.setText("Parking Monlau");
        labelParking.setToolTipText("");

        jPanelParking.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanelParkingLayout = new javax.swing.GroupLayout(jPanelParking);
        jPanelParking.setLayout(jPanelParkingLayout);
        jPanelParkingLayout.setHorizontalGroup(
            jPanelParkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        jPanelParkingLayout.setVerticalGroup(
            jPanelParkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        buttonLiberar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonLiberar.setText("LIBERAR PLAZA");
        buttonLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLiberarActionPerformed(evt);
            }
        });

        buttonAsignar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonAsignar.setText("ASIGNAR PLAZA");
        buttonAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAsignarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/monlau-fp-es.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAsignar)
                .addGap(82, 82, 82)
                .addComponent(buttonLiberar)
                .addGap(126, 126, 126))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(97, 97, 97)
                        .addComponent(labelParking, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelParking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelParking, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(43, 43, 43)
                .addComponent(jPanelParking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAsignar)
                    .addComponent(buttonLiberar))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAsignarActionPerformed
        // TODO add your handling code here:
//        DataClass.JFH.setVisible(false);
//        DataClass.JFP.setVisible(true);
        DataClass.goToAnotherFrame(this, DataClass.JFAP);
    }//GEN-LAST:event_buttonAsignarActionPerformed

    private void buttonLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLiberarActionPerformed
        // TODO add your handling code here:
//        DataClass.JFH.setVisible(false);
//        DataClass.JFPL.setVisible(true);
        DataClass.goToAnotherFrame(this, DataClass.JFLP);
    }//GEN-LAST:event_buttonLiberarActionPerformed

    private void configParkingGrid() throws NotFreePlacesException {
        
        jPanelParking.removeAll(); // Limpiar el panel antes de actualizar

        // Lista de tarifas
        Map<EnumVehiculo, Double> tarifas = new HashMap<>();
        tarifas.put(EnumVehiculo.COCHE, 5.0);
        tarifas.put(EnumVehiculo.MOTO, 3.0);
        tarifas.put(EnumVehiculo.CAMION, 1.0);
        
        // Crear una instancia de Parking (esto es solo un ejemplo, asegúrate de tener los parámetros correctos)
        Parking parking = new Parking(123, "Parking Monlau", "C/ Monlau 6, Barcelona", "+34 666 66 66", 3, 10, tarifas);

        DataClass.setParking(parking);

        // Verificar que el parking no es null antes de usarlo
        if (DataClass.getParking() == null) {
            System.out.println("Error: No se ha asignado un Parking");
            return;
        }

        labelParking.setText(parking.getNombre());

        // Obtener las plazas desde la instancia de Parking
        ArrayList<ArrayList<Plaza>> listaPlazas = parking.getListaPlazas();

        // Configuramos el GridLayout para que el número de columnas se ajuste a los datos
        int filas = listaPlazas.size();
        int columnas = listaPlazas.get(0).size();
        jPanelParking.setLayout(new java.awt.GridLayout(filas, columnas, 10, 50));

        for (ArrayList<Plaza> piso : listaPlazas) {
            for (Plaza plaza : piso) {
                JLabel label = new JLabel("Plaza " + plaza.getNumeroPlaza(), javax.swing.SwingConstants.CENTER);
                label.setFont(new Font("Segoe UI", Font.PLAIN, 14));
                label.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLACK));

                // Color de fondo según si la plaza está ocupada o libre
                if (plaza.isOcupada()) {
                    label.setBackground(java.awt.Color.RED);  // Ocupada
                } else {
                    label.setBackground(java.awt.Color.GREEN); // Libre
                }
                label.setOpaque(true);

                jPanelParking.add(label); // Añadimos la etiqueta al panel
            }
        }

        // Revalidamos y repintamos el panel para que los cambios sean reflejados
        jPanelParking.revalidate();
        jPanelParking.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrameHome().setVisible(true);
                } catch (NotFreePlacesException ex) {
                    Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAsignar;
    private javax.swing.JButton buttonLiberar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelParking;
    private javax.swing.JLabel labelParking;
    // End of variables declaration//GEN-END:variables

    // Método para actualizar el estado de las plazas
    public void actualizarGrid(Parking parking) {
        jPanelParking.removeAll(); // Limpiar el panel antes de actualizar

        // Obtener las plazas desde la instancia de Parking
        ArrayList<ArrayList<Plaza>> listaPlazas = parking.getListaPlazas();

        // Configuramos el GridLayout para que el número de columnas se ajuste a los datos
        int filas = listaPlazas.size();
        int columnas = listaPlazas.get(0).size();
        jPanelParking.setLayout(new java.awt.GridLayout(filas, columnas, 10, 50));

        // Crear y agregar las etiquetas al panel de acuerdo con el estado de cada plaza
        for (ArrayList<Plaza> piso : listaPlazas) {
            for (Plaza plaza : piso) {
                JLabel label = new JLabel("Plaza " + plaza.getNumeroPlaza(), javax.swing.SwingConstants.CENTER);
                label.setFont(new Font("Segoe UI", Font.PLAIN, 14));
                label.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLACK));

                // Color de fondo según si la plaza está ocupada o libre
                if (plaza.isOcupada()) {
                    label.setBackground(java.awt.Color.RED);  // Ocupada
                } else {
                    label.setBackground(java.awt.Color.GREEN); // Libre
                }
                label.setOpaque(true);

                jPanelParking.add(label); // Añadimos la etiqueta al panel
            }
        }

        // Revalidamos y repintamos el panel para que los cambios sean reflejados
        jPanelParking.revalidate();
        jPanelParking.repaint();
    }
}
