/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import control.DataClass;
import static control.DataClass.JFH;
import javax.swing.JOptionPane;
import model.Parking;
import model.Vehiculo;
import model.data.enums.EnumColor;
import model.data.enums.EnumVehiculo;
import model.data.exceptions.NotFreePlacesException;

/**
 *
 * @author ivansimmer
 */
public class JFrameAsignarPlaza extends javax.swing.JFrame {

    private Parking parking;

    /**
     * Creates new form JFrameHome
     */
    public JFrameAsignarPlaza() {
        initComponents();
        configColores();
        configVehiculos();

        parking = DataClass.getParking();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelTipoVehiculo = new javax.swing.JLabel();
        jLabelMatricula = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jComboBoxVehiculos = new javax.swing.JComboBox<>();
        jComboBoxColores = new javax.swing.JComboBox<>();
        jButtonAsigna = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asignar una plaza");

        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("ASIGNA UNA PLAZA");
        jLabel1.setToolTipText("");

        jLabelTipoVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTipoVehiculo.setText("Tipo de vehiculo:");

        jLabelMatricula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelMatricula.setText("Matricula:");

        jLabelColor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelColor.setText("Color:");

        jTextFieldMatricula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jComboBoxVehiculos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBoxVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVehiculosActionPerformed(evt);
            }
        });

        jComboBoxColores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButtonAsigna.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonAsigna.setForeground(new java.awt.Color(255, 0, 0));
        jButtonAsigna.setText("ASIGNA");
        jButtonAsigna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignaActionPerformed(evt);
            }
        });

        jTextAreaResultado.setColumns(20);
        jTextAreaResultado.setRows(5);
        jScrollPane1.setViewportView(jTextAreaResultado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(buttonBack)
                .addGap(0, 636, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelMatricula)
                                .addGap(57, 57, 57)
                                .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelTipoVehiculo)
                                .addGap(34, 34, 34)
                                .addComponent(jComboBoxVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelColor)
                                .addGap(43, 43, 43)
                                .addComponent(jComboBoxColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jButtonAsigna)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(buttonBack)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMatricula)
                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoVehiculo)
                    .addComponent(jComboBoxVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelColor)
                    .addComponent(jComboBoxColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAsigna)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
//        DataClass.JFA.setVisible(false);
//        DataClass.JFH.setVisible(true);
        DataClass.goToAnotherFrame(this, DataClass.JFH);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void jComboBoxVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVehiculosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxVehiculosActionPerformed

    private void jButtonAsignaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignaActionPerformed
        // TODO add your handling code here:
        if (DataClass.getParking() != null) {
            String matricula = jTextFieldMatricula.getText();

            // Verificamos si la matrícula está vacía
            if (matricula.isEmpty()) {
                JOptionPane.showMessageDialog(this, "La matrícula no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                // Obtenemos los valores seleccionados por el usuario
                String tipoVehiculoSeleccionado = jComboBoxVehiculos.getSelectedItem().toString();
                String colorSeleccionado = jComboBoxColores.getSelectedItem().toString();

                // Convertimos los valores seleccionados a los tipos adecuados (Enum)
                EnumVehiculo tipoVehiculo = EnumVehiculo.valueOf(tipoVehiculoSeleccionado);
                EnumColor colorVehiculo = EnumColor.valueOf(colorSeleccionado);

                // Creamos el objeto Vehiculo
                Vehiculo vehiculo = new Vehiculo(tipoVehiculo, matricula, colorVehiculo);

                try {
                    // Usamos DataClass.getParking() para obtener el objeto Parking
                    String resultado = DataClass.getParking().asignarPlaza(vehiculo);

                    // Mostramos el resultado de la asignación en el área de texto
                    jTextAreaResultado.setText(resultado);
                    JFH.actualizarGrid(DataClass.getParking());
                } catch (NotFreePlacesException e) {
                    // Si no hay plazas libres, mostramos un mensaje de error
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            // Si el parking no está inicializado, mostramos un mensaje de error
            JOptionPane.showMessageDialog(this, "No hay un parking asignado. Por favor, inicializa el parking.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAsignaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFrameAsignarPlaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFrameAsignarPlaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFrameAsignarPlaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFrameAsignarPlaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFrameAsignarPlaza().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton jButtonAsigna;
    private javax.swing.JComboBox<String> jComboBoxColores;
    private javax.swing.JComboBox<String> jComboBoxVehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelTipoVehiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaResultado;
    private javax.swing.JTextField jTextFieldMatricula;
    // End of variables declaration//GEN-END:variables

    private void configColores() {
        for (EnumColor color : EnumColor.values()) {
            jComboBoxColores.addItem(color.toString());
        }
    }

    private void configVehiculos() {
        for (EnumVehiculo vehiculo : EnumVehiculo.values()) {
            jComboBoxVehiculos.addItem(vehiculo.toString());
        }
    }
}
